version: "3"

services:
  pocketbase:
    image: augustodelg/pocketbase:latest
    restart: unless-stopped
    ports:
      - 8090:8090
    volumes:
      - pocketbase-data:/pb_data
volumes:
  pocketbase-data:
